import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/app/components/Navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Side Project',
  description: 'Generated by Cesar Mayo',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
